name: splitimize-backend
region: sgp1

services:
  - name: backend-api
    github:
      repo: your-username/your-repo-name
      branch: main
      deploy_on_push: true

    # Build configuration
    build_command: npm run build:backend

    # Run configuration
    run_command: npm run start --workspace=backend-express

    # Environment setup
    source_dir: /

    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        scope: BUILD_AND_RUN_TIME
        type: SECRET
      - key: BETTER_AUTH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: BETTER_AUTH_URL
        value: https://${APP_DOMAIN}
      - key: GOOGLE_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GOOGLE_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: GITHUB_CLIENT_ID
        scope: RUN_TIME
        type: SECRET
      - key: GITHUB_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: FRONTEND_URL
        value: https://your-frontend-url.netlify.app
      - key: GEMINI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: PORT
        value: "8080"

    http_port: 8080

    instance_count: 1
    instance_size_slug: basic-xxs
